CREATE EXTENSION pgcrypto;
CREATE TABLE IF NOT EXISTS persons (
 ID UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
 FIRST_NAME VARCHAR(255) NOT NULL,
 LAST_NAME VARCHAR(255) NOT NULL,
 CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE persons OWNER TO postgres;
